### ISSUE TITLE
When installing this package on ATOM 1.17.2, my packages menu shows empty

### ISSUE THREAD

**Issue by dtiziani** [rapgenic/menu-editor#1]
As soon as I install this package and restart Atom, my packages menu shows as empty.
I've been looking for a package like that, as my menus are cluttered, but it seems to break something.
How can I send some log to help fix the issue? This would rock my Atom if it worked, keep the nice work!!

Here's a print showing the issue
![image](https://user-images.githubusercontent.com/11280919/27033299-0f5945c0-4f4f-11e7-9a21-b9b591a09a1c.png)

**Comment by rapgenic** [comment]
@dtiziani Thanks for submitting this issue. I'm sorry that happened, but this package is in very early development stage... Anyway I am able to reproduce it in a clean Atom installation, and I think I have found the bug. If everything goes well I'm going to push a new release by tomorrow.

**Comment by rapgenic** [comment]
I've just pushed a patch, let me know if it's working now :)

**Comment by dtiziani** [comment]
Hi @rapgenic , it worked now, thanks! Just checking: now it's hiding alright the subitems from package. Is it possible to hide the menu for a package? For instance: 'Packages->TreeView' and others? Right now I can only manage to hide their subitems.

Thanks a lot for the help!

**Comment by rapgenic** [comment]
At the moment no, but that's a feature I've been thinking about. It should be in the next release :)

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
